<?xml version="1.0" encoding="UTF-8"?>
<Layout version="1.6.1">
  <Mode>Vertical</Mode>
  <X>2587</X>
  <Y>247</Y>
  <VerticalWidth>270</VerticalWidth>
  <VerticalHeight>394</VerticalHeight>
  <HorizontalWidth>-1</HorizontalWidth>
  <HorizontalHeight>-1</HorizontalHeight>
  <Settings>
    <TextColor>FFFFFFFF</TextColor>
    <BackgroundColor>FF000000</BackgroundColor>
    <BackgroundColor2>00000000</BackgroundColor2>
    <ThinSeparatorsColor>03FFFFFF</ThinSeparatorsColor>
    <SeparatorsColor>24FFFFFF</SeparatorsColor>
    <PersonalBestColor>FFFFA6FF</PersonalBestColor>
    <AheadGainingTimeColor>FFCC52CC</AheadGainingTimeColor>
    <AheadLosingTimeColor>FFCC88CC</AheadLosingTimeColor>
    <BehindGainingTimeColor>FFCC5252</BehindGainingTimeColor>
    <BehindLosingTimeColor>FFCC0000</BehindLosingTimeColor>
    <BestSegmentColor>FFD8AF1F</BestSegmentColor>
    <UseRainbowColor>False</UseRainbowColor>
    <NotRunningColor>FFACACAC</NotRunningColor>
    <PausedColor>FF7A7A7A</PausedColor>
    <ShadowsColor>80000000</ShadowsColor>
    <TimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAZEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TimesFont>
    <TimerFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAdDYWxpYnJpAAAvQgX8////GFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQEAAAAHdmFsdWVfXwAIAgAAAAEAAAAF+////xtTeXN0ZW0uRHJhd2luZy5HcmFwaGljc1VuaXQBAAAAB3ZhbHVlX18ACAIAAAACAAAACw==]]></TimerFont>
    <TextFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAZEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></TextFont>
    <AlwaysOnTop>True</AlwaysOnTop>
    <ShowBestSegments>False</ShowBestSegments>
    <AntiAliasing>True</AntiAliasing>
    <DropShadows>True</DropShadows>
    <BackgroundType>SolidColor</BackgroundType>
    <BackgroundImage />
    <ImageOpacity>1</ImageOpacity>
    <ImageBlur>0</ImageBlur>
    <Opacity>1</Opacity>
  </Settings>
  <Components>
    <Component>
      <Path>LiveSplit.Title.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <ShowAttemptCount>True</ShowAttemptCount>
        <ShowFinishedRunsCount>False</ShowFinishedRunsCount>
        <OverrideTitleFont>False</OverrideTitleFont>
        <OverrideTitleColor>False</OverrideTitleColor>
        <TitleFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></TitleFont>
        <CenterTitle>False</CenterTitle>
        <SingleLine>False</SingleLine>
        <TitleColor>FFFFFFFF</TitleColor>
        <BackgroundColor>FF090909</BackgroundColor>
        <BackgroundColor2>FF000000</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DisplayGameIcon>False</DisplayGameIcon>
        <ShowRegion>False</ShowRegion>
        <ShowPlatform>False</ShowPlatform>
        <ShowVariables>True</ShowVariables>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Subsplits.dll</Path>
      <Settings>
        <Version>1.6.0</Version>
        <CurrentSplitTopColor>FF555555</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF000000</CurrentSplitBottomColor>
        <VisualSplitCount>15</VisualSplitCount>
        <SplitPreviewCount>4</SplitPreviewCount>
        <DisplayIcons>True</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>True</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <ShowSplitTimes>False</ShowSplitTimes>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>FFFFFFFF</BeforeTimesColor>
        <CurrentTimesColor>FFFFFFFF</CurrentTimesColor>
        <AfterTimesColor>FFFFFFFF</AfterTimesColor>
        <OverrideTimesColor>False</OverrideTimesColor>
        <ShowBlankSplits>True</ShowBlankSplits>
        <LockLastSplit>False</LockLastSplit>
        <IconSize>25</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>0</SplitHeight>
        <CurrentSplitGradient>Horizontal</CurrentSplitGradient>
        <BackgroundColor>FF000000</BackgroundColor>
        <BackgroundColor2>FF070707</BackgroundColor2>
        <BackgroundGradient>Alternating</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>True</DropDecimals>
        <OverrideDeltasColor>False</OverrideDeltasColor>
        <DeltasColor>FFFFFFFF</DeltasColor>
        <Comparison>Personal Best</Comparison>
        <Display2Rows>False</Display2Rows>
        <IndentBlankIcons>True</IndentBlankIcons>
        <IndentSubsplits>True</IndentSubsplits>
        <HideSubsplits>False</HideSubsplits>
        <ShowSubsplits>False</ShowSubsplits>
        <CurrentSectionOnly>False</CurrentSectionOnly>
        <OverrideSubsplitColor>True</OverrideSubsplitColor>
        <SubsplitGradient>Plain</SubsplitGradient>
        <ShowHeader>True</ShowHeader>
        <IndentSectionSplit>True</IndentSectionSplit>
        <ShowIconSectionSplit>True</ShowIconSectionSplit>
        <ShowSectionIcon>False</ShowSectionIcon>
        <HeaderGradient>Vertical</HeaderGradient>
        <OverrideHeaderColor>True</OverrideHeaderColor>
        <HeaderText>True</HeaderText>
        <HeaderTimes>False</HeaderTimes>
        <HeaderAccuracy>Tenths</HeaderAccuracy>
        <SectionTimer>False</SectionTimer>
        <SectionTimerGradient>False</SectionTimerGradient>
        <SectionTimerAccuracy>Tenths</SectionTimerAccuracy>
        <SubsplitTopColor>8D000000</SubsplitTopColor>
        <SubsplitBottomColor>00FFFFFF</SubsplitBottomColor>
        <HeaderTopColor>FF2A2A2A</HeaderTopColor>
        <HeaderBottomColor>FF231225</HeaderBottomColor>
        <HeaderTextColor>FFFFFFFF</HeaderTextColor>
        <HeaderTimesColor>00271F28</HeaderTimesColor>
        <SectionTimerColor>FFFFFFFF</SectionTimerColor>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Text.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FF000000</TimeColor>
        <OverrideTimeColor>True</OverrideTimeColor>
        <BackgroundColor>FF000000</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Text1>%:</Text1>
        <Text2>.</Text2>
        <Font1><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAkEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></Font1>
        <Font2><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></Font2>
        <OverrideFont1>True</OverrideFont1>
        <OverrideFont2>False</OverrideFont2>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Splits.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <CurrentSplitTopColor>FF000000</CurrentSplitTopColor>
        <CurrentSplitBottomColor>FF000000</CurrentSplitBottomColor>
        <VisualSplitCount>1</VisualSplitCount>
        <SplitPreviewCount>0</SplitPreviewCount>
        <DisplayIcons>False</DisplayIcons>
        <ShowThinSeparators>False</ShowThinSeparators>
        <AlwaysShowLastSplit>False</AlwaysShowLastSplit>
        <SplitWidth>20</SplitWidth>
        <SplitTimesAccuracy>Seconds</SplitTimesAccuracy>
        <AutomaticAbbreviations>False</AutomaticAbbreviations>
        <BeforeNamesColor>FFFFFFFF</BeforeNamesColor>
        <CurrentNamesColor>FFFFFFFF</CurrentNamesColor>
        <AfterNamesColor>FFFFFFFF</AfterNamesColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BeforeTimesColor>00000000</BeforeTimesColor>
        <CurrentTimesColor>00000000</CurrentTimesColor>
        <AfterTimesColor>00000000</AfterTimesColor>
        <OverrideTimesColor>True</OverrideTimesColor>
        <ShowBlankSplits>False</ShowBlankSplits>
        <LockLastSplit>True</LockLastSplit>
        <IconSize>24</IconSize>
        <IconShadows>True</IconShadows>
        <SplitHeight>0</SplitHeight>
        <CurrentSplitGradient>Vertical</CurrentSplitGradient>
        <BackgroundColor>FF000000</BackgroundColor>
        <BackgroundColor2>FF000000</BackgroundColor2>
        <BackgroundGradient>Alternating</BackgroundGradient>
        <SeparatorLastSplit>True</SeparatorLastSplit>
        <DeltasAccuracy>Tenths</DeltasAccuracy>
        <DropDecimals>False</DropDecimals>
        <OverrideDeltasColor>True</OverrideDeltasColor>
        <DeltasColor>00FF0000</DeltasColor>
        <Display2Rows>True</Display2Rows>
        <ShowColumnLabels>False</ShowColumnLabels>
        <LabelsColor>FFFFFFFF</LabelsColor>
        <Columns>
          <Settings>
            <Version>1.5</Version>
            <Name>+/-</Name>
            <Type>DeltaorSplitTime</Type>
            <Comparison>Current Comparison</Comparison>
            <TimingMethod>Current Timing Method</TimingMethod>
          </Settings>
        </Columns>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.DetailedTimer.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>69</Height>
        <Width>200</Width>
        <SegmentTimerSizeRatio>37</SegmentTimerSizeRatio>
        <TimerShowGradient>True</TimerShowGradient>
        <OverrideTimerColors>False</OverrideTimerColors>
        <SegmentTimerShowGradient>True</SegmentTimerShowGradient>
        <TimerFormat>1.23</TimerFormat>
        <SegmentTimerFormat>1.23</SegmentTimerFormat>
        <SegmentTimesAccuracy>Hundredths</SegmentTimesAccuracy>
        <TimerColor>FFAAAAAA</TimerColor>
        <SegmentTimerColor>FFAAAAAA</SegmentTimerColor>
        <SegmentLabelsColor>FFFFFFFF</SegmentLabelsColor>
        <SegmentTimesColor>FFFFFFFF</SegmentTimesColor>
        <SegmentLabelsFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAQEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SegmentLabelsFont>
        <SegmentTimesFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAABFTZWdvZSBVSSBTZW1pYm9sZAAANEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAABAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SegmentTimesFont>
        <SplitNameFont><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAABEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAwAAAAs=]]></SplitNameFont>
        <DisplayIcon>False</DisplayIcon>
        <IconSize>34</IconSize>
        <ShowSplitName>False</ShowSplitName>
        <SplitNameColor>FFFFFFFF</SplitNameColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Comparison2>Best Segments</Comparison2>
        <HideComparison>False</HideComparison>
        <TimingMethod>Current Timing Method</TimingMethod>
        <DecimalsSize>35</DecimalsSize>
        <SegmentTimerDecimalsSize>35</SegmentTimerDecimalsSize>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.Graph.dll</Path>
      <Settings>
        <Version>1.5</Version>
        <Height>50</Height>
        <Width>180</Width>
        <BehindGraphColor>FF732F2F</BehindGraphColor>
        <AheadGraphColor>FF231225</AheadGraphColor>
        <GridlinesColor>50000000</GridlinesColor>
        <PartialFillColorBehind>70000000</PartialFillColorBehind>
        <CompleteFillColorBehind>AA000000</CompleteFillColorBehind>
        <PartialFillColorAhead>70000000</PartialFillColorAhead>
        <CompleteFillColorAhead>AA000000</CompleteFillColorAhead>
        <GraphColor>FFFFFFFF</GraphColor>
        <ShadowsColor>38000000</ShadowsColor>
        <GraphLinesColor>26FFFFFF</GraphLinesColor>
        <LiveGraph>True</LiveGraph>
        <FlipGraph>False</FlipGraph>
        <Comparison>Current Comparison</Comparison>
        <ShowBestSegments>False</ShowBestSegments>
        <GraphGoldColor>FFFFD700</GraphGoldColor>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.PreviousSegment.dll</Path>
      <Settings>
        <Version>1.6</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <DeltaAccuracy>Tenths</DeltaAccuracy>
        <DropDecimals>True</DropDecimals>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
        <ShowPossibleTimeSave>False</ShowPossibleTimeSave>
        <TimeSaveAccuracy>Tenths</TimeSaveAccuracy>
      </Settings>
    </Component>
    <Component>
      <Path>LiveSplit.RunPrediction.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FFFFFFFF</TimeColor>
        <OverrideTimeColor>False</OverrideTimeColor>
        <Accuracy>Hundredths</Accuracy>
        <BackgroundColor>00FFFFFF</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Comparison>Current Comparison</Comparison>
        <Display2Rows>False</Display2Rows>
      </Settings>
    </Component>
    <Component>
      <Path>
      </Path>
      <Settings />
    </Component>
    <Component>
      <Path>LiveSplit.Text.dll</Path>
      <Settings>
        <Version>1.4</Version>
        <TextColor>FFFFFFFF</TextColor>
        <OverrideTextColor>False</OverrideTextColor>
        <TimeColor>FF000000</TimeColor>
        <OverrideTimeColor>True</OverrideTimeColor>
        <BackgroundColor>00101010</BackgroundColor>
        <BackgroundColor2>00FFFFFF</BackgroundColor2>
        <BackgroundGradient>Plain</BackgroundGradient>
        <Text1>Input:</Text1>
        <Text2>.</Text2>
        <Font1><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></Font1>
        <Font2><![CDATA[AAEAAAD/////AQAAAAAAAAAMAgAAAFFTeXN0ZW0uRHJhd2luZywgVmVyc2lvbj00LjAuMC4wLCBDdWx0dXJlPW5ldXRyYWwsIFB1YmxpY0tleVRva2VuPWIwM2Y1ZjdmMTFkNTBhM2EFAQAAABNTeXN0ZW0uRHJhd2luZy5Gb250BAAAAAROYW1lBFNpemUFU3R5bGUEVW5pdAEABAQLGFN5c3RlbS5EcmF3aW5nLkZvbnRTdHlsZQIAAAAbU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AgAAAAIAAAAGAwAAAAhTZWdvZSBVSQAAUEEF/P///xhTeXN0ZW0uRHJhd2luZy5Gb250U3R5bGUBAAAAB3ZhbHVlX18ACAIAAAAAAAAABfv///8bU3lzdGVtLkRyYXdpbmcuR3JhcGhpY3NVbml0AQAAAAd2YWx1ZV9fAAgCAAAAAgAAAAs=]]></Font2>
        <OverrideFont1>False</OverrideFont1>
        <OverrideFont2>False</OverrideFont2>
        <Display2Rows>True</Display2Rows>
      </Settings>
    </Component>
  </Components>
</Layout>